[package]
name = "webextension-protocol"
version = "0.1.0"
authors = ["Krzysztof Jan Modras <chrmod@chrmod.net>"]
description = "Webextension native messaging protocol helpers"
license = "AGPL-3.0"

[dependencies]
byteorder = "1.0.0"

[lib]
